name: Development Build and Deploy

on:
  push:
    branches: [ develop, dev ]
  pull_request:
    branches: [ develop, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Run type checking
      run: npm run type-check
      
    - name: Run tests
      run: npm run test
      
    - name: Build development
      run: npm run build:dev
      env:
        NODE_ENV: development
        NEXT_PUBLIC_APP_ENV: development
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dev-build
        path: .next/
        
  deploy-dev:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/dev'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build for development
      run: npm run build:dev
      env:
        NODE_ENV: development
        NEXT_PUBLIC_APP_ENV: development
        NEXT_PUBLIC_APP_URL: ${{ secrets.DEV_APP_URL }}
        NEXT_PUBLIC_API_URL: ${{ secrets.DEV_API_URL }}
        NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.DEV_FIREBASE_API_KEY }}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.DEV_FIREBASE_AUTH_DOMAIN }}
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.DEV_FIREBASE_PROJECT_ID }}
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.DEV_FIREBASE_STORAGE_BUCKET }}
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.DEV_FIREBASE_MESSAGING_SENDER_ID }}
        NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.DEV_FIREBASE_APP_ID }}
        NEXT_PUBLIC_OPENAI_API_KEY: ${{ secrets.DEV_OPENAI_API_KEY }}
        NEXT_PUBLIC_GEMINI_API_KEY: ${{ secrets.DEV_GEMINI_API_KEY }}
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.DEV_STRIPE_PUBLISHABLE_KEY }}
        STRIPE_SECRET_KEY: ${{ secrets.DEV_STRIPE_SECRET_KEY }}
        NEXT_PUBLIC_GA_TRACKING_ID: ${{ secrets.DEV_GA_TRACKING_ID }}
        
    - name: Deploy to Vercel (Development)
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./
        vercel-args: '--prod=false'
