name: Security Scan

on:
  push:
    branches: [ main, staging, develop ]
  pull_request:
    branches: [ main, staging ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level=moderate
      
    - name: Run ESLint security rules
      run: npx eslint . --ext .ts,.tsx,.js,.jsx --config .eslintrc.json
      
    - name: Check for secrets
      run: |
        # Check for hardcoded secrets
        if grep -r "password\|secret\|key\|token" --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" src/ | grep -v "process.env"; then
          echo "❌ Potential secrets found in code"
          exit 1
        fi
        
    - name: Check security headers
      run: |
        # Verify security middleware exists
        if [ ! -f "src/middleware.ts" ]; then
          echo "❌ Security middleware missing"
          exit 1
        fi
        
    - name: Check rate limiting
      run: |
        # Verify rate limiting is implemented
        if ! grep -r "rateLimit" src/app/api/; then
          echo "❌ Rate limiting not implemented in API routes"
          exit 1
        fi
        
    - name: Check CSRF protection
      run: |
        # Verify CSRF protection is implemented
        if [ ! -f "src/lib/csrf.ts" ]; then
          echo "❌ CSRF protection missing"
          exit 1
        fi
        
    - name: Check input validation
      run: |
        # Verify input validation is implemented
        if [ ! -f "src/lib/input-validation.ts" ]; then
          echo "❌ Input validation missing"
          exit 1
        fi
        
    - name: Check encryption
      run: |
        # Verify PII encryption is implemented
        if [ ! -f "src/lib/encryption.ts" ]; then
          echo "❌ PII encryption missing"
          exit 1
        fi
        
    - name: Check monitoring
      run: |
        # Verify monitoring is implemented
        if [ ! -f "src/lib/monitoring.ts" ]; then
          echo "❌ Error monitoring missing"
          exit 1
        fi
        
    - name: Security scan summary
      run: |
        echo "✅ Security scan completed successfully"
        echo "🔒 All critical security features verified"


